apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tiketi
  namespace: argocd
spec:
  description: Tiketi production deployment
  sourceRepos:
    - 'https://github.com/<ORG>/project-ticketing.git'
  destinations:
    - namespace: tiketi
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
