apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tiketi-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tiketi
  source:
    repoURL: 'https://github.com/cchriscode/tiketi.git'
    targetRevision: final
    path: argocd/applications
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
